# permissions for end users to edit mazes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maze-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: maze-editor-role
rules:
- apiGroups:
  - maze.staticvoid.io
  resources:
  - mazes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maze.staticvoid.io
  resources:
  - mazes/status
  verbs:
  - get
