---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maze.staticvoid.io
  resources:
  - mazes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maze.staticvoid.io
  resources:
  - mazes/finalizers
  verbs:
  - update
- apiGroups:
  - maze.staticvoid.io
  resources:
  - mazes/status
  verbs:
  - get
  - patch
  - update
