apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-maze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-maze
  template:
    metadata:
      labels:
        app: kube-maze
    spec:
      containers:
      - name: kube-maze-backend
        image: vfiftyfive/kube-maze-backend:0.1
        ports:
        - containerPort: 8080
      - name: kube-maze-frontend
        image: vfiftyfive/kube-maze-frontend:0.1
        env:
        - name: REACT_APP_CHEAT_MODE
          value: "true"
        - name: REACT_APP_MAZE_SIZE
          value: "25"
        - name: REACT_APP_BACKEND_URL
          value: "http://localhost:8080"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-maze
spec:
  type: ClusterIP
  selector:
    app: kube-maze
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
   

